
image: Ubuntu1804

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar -port=7777 &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info "-Dselenide.headless=true" # запускаем тест, флаг --info позволяет выводить больше информации

